### PR TITLE
feat: initial release

### PR DESCRIPTION
**Pull request by keithamus**
@lucasfcosta to get semantic-release to pick up the releases (even if its the first one) we need to have a commit marked as `feat` or `fix`. This should trigger a release on build.

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Thank you for the explanation, unfortunately I only noticed this with your PR to pathval.
I'll start using it :smile: 

LGTM

**Comment by keithamus** [comment]
@meeber @shvaikalesh @vieiralucas can we get approval from one of you please?

**Comment by shvaikalesh** [comment]
LGTM

**Comment by lucasfcosta** [comment]
@keithamus We need to change this module's name before releasing, I opened a PR for that so I'm not sure if this will be needed. What do you guys think?
I'd love to hear your opinion on #5 so we can get an available namespace on NPM ASAP.

Thanks everyone!

**Pull request closed without merging**
