### PR TITLE
Add travis keys

### PR DESCRIPTION
**Pull request by keithamus**
@lucasfcosta @meeber @shvaikalesh this should get travis deploying properly.

### CODE REVIEW

**Comment by shvaikalesh** [comment]
LGTM

**Comment by meeber** [comment]
LGTM

**Comment by lucasfcosta** [comment]
LGTM, thanks for this @keithamus 😄

**Comment by lucasfcosta** [comment]
Testing again so we can merge this: LGTM

**Comment by vieiralucas** [comment]
Let me try: LGTM

**Comment by keithamus** [comment]
LGTM seemed broken, but it's clear we have consensus so I've just merged 😆

**Pull request merged**
