### PR TITLE
chore: BREAKING CHANGE getFuncName returning null for non-function arguments

### PR DESCRIPTION
**Pull request by lucasfcosta**
Hey friends, I forgot to include `BREAKING CHANGE` into the last commit message in order to release our change.

This is an empty commit created only for us to trigger a release to NPM.

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Ping @keithamus @vieiralucas @shvaikalesh @meeber 
Hey friends, apparently adding `BREAKING CHANGE` to the commit message didn't work.

Any ideas on how to release this?

**Comment by keithamus** [comment]
It needs to follow this format:

```
chore: <the message>

BREAKING CHANGE:
<how things broke>
```

**Comment by lucasfcosta** [comment]
@keithamus I tried to add `BREAKING CHANGE:` to the start of the commit message, but the commit message checks didn't allow me to 😢 

```
$ git commit --allow-empty -m "BREAKING CHANGE: getFuncName returning null for non-function arguments"
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
BREAKING CHANGE: getFuncName returning null for non-function arguments
```

**Comment by meeber** [comment]
First line needs to be `chore: <message>`
Then (optional?) blank line.
Then next line needs to be `BREAKING CHANGE:` (with the colon)
The description of the breaking change can be either on the same line as above or on new line.

**Comment by lucasfcosta** [comment]
Ah that makes sense. I'll try it! Thanks @meeber and @keithamus !

**Comment by keithamus** [comment]
@lucasfcosta to help write commit messages that follow this format, you could use [commitizen](https://github.com/commitizen/cz-cli):

```shell
$ npm i -g commitizen
$ npm i -g cz-conventional-changelog 
$ echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc
$ git cz
cz-cli@2.9.5, cz-conventional-changelog@1.2.0


Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing:
feat:     A new feature
? Denote the scope of this change ($location, $browser, $compile, etc.):
 getFuncName
? Write a short, imperative tense description of the change:
 returns null for non-function arguments
? Provide a longer description of the change:
? List any breaking changes or issues closed by this change:
 BREAKING CHANGE: now returns null if passed a non function
[master cc8d96b] feat(getFuncName):  returns null for non-function arguments

$ git log
commit cc8d96b9f76d4f0cdc06ff200a319579cf5d0a5b
Author: Keith Cirkel <keithamus@users.noreply.github.com>
Date:   Thu Jan 19 21:23:05 2017 +0000

    feat(post):  returns null for non-function arguments

   BREAKING CHANGE: now returns null if passed a non function
```

**Comment by lucasfcosta** [comment]
Oh my god, how have I lived without this for so long.

Thanks @keithamus!

**Pull request merged**
